### 회원가입
POST http://localhost:8080/signup
Content-Type: application/json
Accept: */*

{
  "memberID": "id04",
  "memberPW": "pass04",
  "memberName": "박선영",
  "memberPhone": "010-2222-3333",
  "memberEmail": "user03@gmail.com"
}

### 로그인
POST http://localhost:8080/login
Content-Type: application/json
Accept: */*

{
  "memberID": "id01",
  "memberPW": "pass01"
}

### 아이디 찾기
POST http://localhost:8080/login/findID
Content-Type: application/json
Accept: */*

{
  "memberEmail": "user03@gmail.com"
}

### 비밀번호 찾기
POST http://localhost:8080/login/findPW
Content-Type: application/json
Accept: */*

{
  "memberID": "id03",
  "memberEmail": "user03@gmail.com"
}

### 인증번호 확인
POST http://localhost:8080/login/confirmCode
Content-Type: application/json
Accept: */*

{
  "memberEmail": "user03@gmail.com",
  "emailCode": 253582
}