### 회원가입
POST http://localhost:8080/signup
Content-Type: application/json
Accept: */*

{
  "userId": "user04",
  "userPass": "pass04",
  "userName": "유저4",
  "userEmail": "user04@pde.com",
  "userRole": "ALL"
}

### 로그인
POST http://localhost:8080/login
Content-Type: application/json
Accept: */*

{
  "userId": "user04",
  "userPass": "pass04"
}